server:
  port: 8801

spring:
  redis:
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        min-idle: 8
        max-idle: 100
        max-wait: -1ms
    database: 1
    timeout: 10000ms
    host: localhost