spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 7
    lease-renewal-interval-in-seconds: 3
  client:
    eureka-service-url-poll-interval-seconds: 60
    registry-fetch-interval-seconds: 5
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  server:
    peer-eureka-nodes-update-interval-ms: 60000
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000